-- -- Load oil.nvim
-- require("oil").setup()
--
-- -- Keymap: open parent directory like vinegar
-- vim.keymap.set("n", "-", function()
--   require("oil").open(vim.fn.expand("%:p:h"))
-- end, { desc = "Open parent directory in oil.nvim" })
--
-- require("oil").setup({
--     default_file_explorer = true,
--     delete_to_trash = true,
--     skip_confirm_for_simple_edits = true,
--     view_options = {
--         show_hidden = true,
--         natural_order = true,
--         is_always_hidden = function(name, _)
--             return name == ".." or name == ".git"
--         end,
--     },
--     float = {
--         padding = 2,
--         max_width = 90,
--         max_height = 0,
--     },
--     win_options = {
--         wrap = true,
--         winblend = 0,
--     },
--     keymaps = {
--         ["<C-c>"] = false,
--         ["q"] = "actions.close",
--     },
-- })
